server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brdproject?serverTimezone=Asia/Seoul
    username: choon
    password: Qkrtjdcns1!

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: true
#      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    database: mysql

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false